# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2014.2.dev9.g02dcdc9\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-09 06:05+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/location.py:390
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""

#: glance/scrubber.py:149
#, python-format
msgid "%s file can not be read."
msgstr ""

#: glance/scrubber.py:172
#, python-format
msgid "%s file can not be wrote."
msgstr ""

#: glance/scrubber.py:476
#, python-format
msgid "Can not %(op)s scrub jobs from queue: %(err)s"
msgstr ""

#: glance/scrubber.py:577
#, python-format
msgid "%s file can not be created."
msgstr ""

#: glance/api/common.py:53
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""

#: glance/api/common.py:59
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""

#: glance/api/common.py:90
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/api/middleware/cache.py:169
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""

#: glance/api/middleware/cache.py:268
#, python-format
msgid "could not find %s"
msgstr ""

#: glance/api/middleware/cache.py:287
msgid "Checksum header is missing."
msgstr ""

#: glance/api/v1/images.py:602
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr ""

#: glance/api/v1/upload_utils.py:79
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:240
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v2/image_data.py:61
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr ""

#: glance/api/v2/image_data.py:149
msgid "Failed to upload image data due to HTTP error"
msgstr ""

#: glance/api/v2/image_data.py:154
msgid "Failed to upload image data due to internal error"
msgstr ""

#: glance/api/v2/metadef_namespaces.py:190
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr ""

#: glance/api/v2/metadef_resource_types.py:126
#: glance/tests/functional/v2/test_metadef_resourcetypes.py:129
#, python-format
msgid "Failed to find resource type %(resourcetype)s to delete"
msgstr ""

#: glance/async/__init__.py:67
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""

#: glance/async/__init__.py:71
msgid "Internal error occurred while trying to process task."
msgstr ""

#: glance/common/store_utils.py:68
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr ""

#: glance/common/scripts/__init__.py:40
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment "
"of Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""

#: glance/common/scripts/__init__.py:50
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""

#: glance/common/scripts/utils.py:46
#, python-format
msgid "Task not found for task_id %s"
msgstr ""

#: glance/common/scripts/image_import/main.py:102
#, python-format
msgid ""
"The Image %(image_id)s object being created by this task %(task_id)s, is "
"no longer in valid status for further processing.image_id"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:126
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:62
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:96
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr ""

#: glance/domain/__init__.py:472
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr ""

#: glance/image_cache/__init__.py:268
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:397
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/xattr.py:109
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."
msgstr ""

#: glance/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: glance/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: glance/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: glance/registry/api/v1/images.py:134
msgid "Unable to get images"
msgstr ""

#: glance/registry/api/v1/images.py:352
#, python-format
msgid "Unable to show image %s"
msgstr ""

#: glance/registry/api/v1/images.py:388
#, python-format
msgid "Unable to delete image %s"
msgstr ""

#: glance/registry/api/v1/images.py:440
#, python-format
msgid "Unable to create image %s"
msgstr ""

#: glance/registry/api/v1/images.py:513
#, python-format
msgid "Unable to update image %s"
msgstr ""

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:99
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr ""

